name: Build and test wheels

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux_x86_64
            zip: ubuntu-22.04-binaries.zip
            library_zip_name: libausaxs.so
            library: libausaxs.so

          - os: macos-latest  
            platform: macosx_11_0_universal2
            zip: macos-universal-binaries.zip
            library_zip_name: libausaxs.dylib
            library: libausaxs.dylib

          - os: windows-latest
            platform: win_amd64
            zip: windows-binaries.zip
            library_zip_name: ausaxs.dll
            library: libausaxs.dll

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download and extract platform-specific library
        shell: bash
        run: | 
          echo "Downloading ${{ matrix.zip }} for platform ${{ matrix.platform }}..."
          
          # Try multiple methods to get the download URL
          echo "Fetching release information..."
          RELEASES_JSON=$(curl -s https://api.github.com/repos/AUSAXS/AUSAXS/releases/latest)
          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch release information from GitHub API"
            exit 1
          fi
          
          DOWNLOAD_URL=$(echo "$RELEASES_JSON" | grep "browser_download_url.*${{ matrix.zip }}" | cut -d '"' -f 4)

          if [ -z "$DOWNLOAD_URL" ]; then
            echo "Error: Could not find download URL for ${{ matrix.zip }}"
            echo "Available releases:"
            echo "$RELEASES_JSON" | grep "browser_download_url" | cut -d '"' -f 4
            exit 1
          fi

          echo "Download URL: $DOWNLOAD_URL"
          
          # Download with better error handling
          if ! curl -L -f -o release.zip "$DOWNLOAD_URL"; then
            echo "Error: Failed to download $DOWNLOAD_URL"
            exit 1
          fi
          
          # Verify download
          if [ ! -f release.zip ] || [ ! -s release.zip ]; then
            echo "Error: Downloaded file is missing or empty"
            ls -la release.zip 2>/dev/null || echo "release.zip does not exist"
            exit 1
          fi
          
          echo "Downloaded $(du -h release.zip | cut -f1) successfully"
          
          # Extract with error handling
          if ! unzip -q release.zip; then
            echo "Error: Failed to extract release.zip"
            exit 1
          fi
          mkdir -p pyausaxs/resources
          LIBRARY_PATH=$(find . -name "${{ matrix.library_zip_name }}" -type f | head -n 1)

          if [ -z "$LIBRARY_PATH" ]; then
            echo "Error: Could not find ${{ matrix.library_zip_name }} in extracted files"
            echo "Available library files:"
            find . -name "*.so" -o -name "*.dylib" -o -name "*.dll" | head -10
            echo "Directory structure:"
            find . -type d | head -10
            exit 1
          fi

          cp "$LIBRARY_PATH" "pyausaxs/resources/${{ matrix.library }}"
          echo "Library copied: ${{ matrix.library_zip_name }}"
          ls -la pyausaxs/resources/

      - name: Generate platform-specific pyproject.toml
        shell: bash
        run: |
          sed 's|LIBRARY_PLACEHOLDER|resources/${{ matrix.library }}|' pyproject.template.toml > pyproject.toml
          echo "Generated pyproject.toml for ${{ matrix.platform }}:"
          cat pyproject.toml

      - name: Verify library exists
        shell: bash
        run: |
          if [ ! -f "pyausaxs/resources/${{ matrix.library }}" ]; then
            echo "Error: Library not found at pyausaxs/resources/${{ matrix.library }}"
            ls -la pyausaxs/resources/
            exit 1
          fi

      - name: Build platform-specific wheel
        shell: bash
        run: |
          python -m pip install --upgrade pip build
          python -m build --wheel

      - name: Apply platform tag and add project name
        shell: bash
        run: |
          cd dist
          for wheel in *.whl; do
            # Replace the generic tag with platform-specific tag
            platform_wheel=$(echo "$wheel" | sed 's/-py3-none-any/-py3-none-${{ matrix.platform }}/')
            
            if [ "$wheel" != "$platform_wheel" ]; then
              mv "$wheel" "$platform_wheel"
              echo "Applied platform tag: $wheel -> $platform_wheel"
              wheel="$platform_wheel"
            fi

            echo "Final wheel: $wheel ($(du -h "$wheel" | cut -f1))"
          done

      - name: Test wheel installation
        shell: bash
        run: |
          pip install twine
          twine check dist/*.whl
          rm -rf pyausaxs
          python -m pip install dist/*.whl
          python test/test.py

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.platform }}
          path: dist/*.whl