name: Build wheels with cibuildwheel (Linux only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy native libs into package resources
        run: |
          mkdir -p pyausaxs/resources
          # select the linux shared lib if present at top-level resources/
          if [ -f resources/libausaxs.so ]; then
            cp resources/libausaxs.so pyausaxs/resources/
          fi

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Install built wheel and run tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheelhouse/*.whl
          python test/test.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse
