name: Build wheels with cibuildwheel (Linux only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse
